package reporter

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/google/go-github/v49/github"
	"github.com/rs/zerolog/log"
	"golang.org/x/oauth2"

	"github.com/cloudflare/pint/internal/checks"
	"github.com/cloudflare/pint/internal/git"
)

var (
	reviewBody         = "This review was generated by [pint](https://github.com/cloudflare/pint)."
	reviewEventComment = "COMMENT"
	reviewEventApprove = "APPROVE"
)

type GithubReporter struct {
	baseURL   string
	uploadURL string
	timeout   time.Duration
	authToken string
	owner     string
	repo      string
	prNum     int
	gitCmd    git.CommandRunner

	client *github.Client
}

// NewGithubReporter creates a new GitHub reporter that reports
// problems via comments on a given pull request number (integer).
func NewGithubReporter(baseURL, uploadURL string, timeout time.Duration, token, owner, repo string, prNum int, gitCmd git.CommandRunner) (_ GithubReporter, err error) {
	gr := GithubReporter{
		baseURL:   baseURL,
		uploadURL: uploadURL,
		timeout:   timeout,
		authToken: token,
		owner:     owner,
		repo:      repo,
		prNum:     prNum,
		gitCmd:    gitCmd,
	}

	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: gr.authToken},
	)
	tc := oauth2.NewClient(context.Background(), ts)

	if gr.uploadURL != "" && gr.baseURL != "" {
		gr.client, err = github.NewEnterpriseClient(gr.baseURL, gr.uploadURL, tc)
		if err != nil {
			return gr, fmt.Errorf("creating new GitHub client: %w", err)
		}
	} else {
		gr.client = github.NewClient(tc)
	}

	return gr, nil
}

// Submit submits the summary to GitHub.
func (gr GithubReporter) Submit(summary Summary) error {
	headCommit, err := git.HeadCommit(gr.gitCmd)
	if err != nil {
		return fmt.Errorf("failed to get HEAD commit: %w", err)
	}
	log.Info().Str("commit", headCommit).Msg("Got HEAD commit from git")

	review, err := gr.findExistingReview()
	if err != nil {
		return fmt.Errorf("failed to list pull request reviews: %w", err)
	}
	if review != nil {
		log.Info().Str("commit", headCommit).Msg("Pull request review already exists, updating")
		if err = gr.updateReview(review, headCommit, summary); err != nil {
			return err
		}
	} else {
		log.Info().Str("commit", headCommit).Msg("Creating pull request review")
		if err = gr.createReview(headCommit, summary); err != nil {
			return err
		}
	}

	return gr.addReviewComments(review, headCommit, summary)
}

func (gr GithubReporter) findExistingReview() (*github.PullRequestReview, error) {
	ctx, cancel := context.WithTimeout(context.Background(), gr.timeout)
	defer cancel()

	reviews, _, err := gr.client.PullRequests.ListReviews(ctx, gr.owner, gr.repo, gr.prNum, nil)
	if err != nil {
		return nil, err
	}

	for _, review := range reviews {
		if strings.HasPrefix(review.GetBody(), reviewBody) {
			return review, nil
		}
	}

	return nil, nil
}

func (gr GithubReporter) updateReview(review *github.PullRequestReview, headCommit string, summary Summary) error {
	log.Info().Str("repo", fmt.Sprintf("%s/%s", gr.owner, gr.repo)).Int64("id", review.GetID()).Msg("Updating pull request review")

	ctx, cancel := context.WithTimeout(context.Background(), gr.timeout)
	defer cancel()

	_, _, err := gr.client.PullRequests.UpdateReview(
		ctx,
		gr.owner,
		gr.repo,
		gr.prNum,
		review.GetID(),
		formatGHReviewBody(summary),
	)
	return err
}

func (gr GithubReporter) addReviewComments(review *github.PullRequestReview, headCommit string, summary Summary) error {
	log.Info().Msg("Creating review comments")

	existingComments, err := gr.getReviewComments()
	if err != nil {
		return err
	}

	for _, rep := range summary.Reports() {
		comment := reportToGitHubComment(headCommit, rep)

		var found bool
		for _, ec := range existingComments {
			if ec.GetBody() == comment.GetBody() && ec.GetCommitID() == comment.GetCommitID() {
				found = true
				break
			}
		}
		if found {
			log.Debug().Str("body", comment.GetBody()).Str("commit", comment.GetCommitID()).Msg("Comment already exist")
			continue
		}

		if err := gr.createComment(review, comment); err != nil {
			return err
		}
	}

	return nil
}

func (gr GithubReporter) getReviewComments() ([]*github.PullRequestComment, error) {
	ctx, cancel := context.WithTimeout(context.Background(), gr.timeout)
	defer cancel()

	comments, _, err := gr.client.PullRequests.ListComments(ctx, gr.owner, gr.repo, gr.prNum, nil)
	return comments, err
}

func (gr GithubReporter) createComment(review *github.PullRequestReview, comment *github.PullRequestComment) error {
	log.Debug().Str("body", comment.GetBody()).Str("commit", comment.GetCommitID()).Msg("Creating review comment")

	ctx, cancel := context.WithTimeout(context.Background(), gr.timeout)
	defer cancel()

	_, _, err := gr.client.PullRequests.CreateComment(ctx, gr.owner, gr.repo, gr.prNum, comment)
	return err
}

func (gr GithubReporter) createReview(headCommit string, summary Summary) error {
	log.Info().Str("repo", fmt.Sprintf("%s/%s", gr.owner, gr.repo)).Str("commit", headCommit).Msg("Creating pull request review")

	ctx, cancel := context.WithTimeout(context.Background(), gr.timeout)
	defer cancel()

	_, resp, err := gr.client.PullRequests.CreateReview(
		ctx,
		gr.owner,
		gr.repo,
		gr.prNum,
		&github.PullRequestReviewRequest{
			CommitID: github.String(headCommit),
			Body:     github.String(formatGHReviewBody(summary)),
			Event:    github.String(ghEvent(summary)),
		},
	)
	if err != nil {
		return fmt.Errorf("failed to create review: %w", err)
	}
	log.Info().Str("status", resp.Status).Msg("Pull request review created")
	return nil
}

func formatGHReviewBody(summary Summary) string {
	var b strings.Builder

	b.WriteString(reviewBody)
	b.WriteString("\n\nSummary:\n")

	b.WriteString("| Severity | Number of problems |\n")
	b.WriteString("| --- | --- |\n")
	bySeverity := summary.CountBySeverity()
	for _, s := range []checks.Severity{checks.Fatal, checks.Bug, checks.Warning, checks.Information} {
		if bySeverity[s] > 0 {
			b.WriteString("| ")
			b.WriteString(s.String())
			b.WriteString(" | ")
			b.WriteString(strconv.Itoa(bySeverity[s]))
			b.WriteString(" |\n")
		}
	}

	return b.String()
}

func ghEvent(summary Summary) string {
	for _, rep := range summary.Reports() {
		if rep.Problem.Severity > checks.Information {
			return reviewEventComment
		}
	}
	return reviewEventApprove
}

func reportToGitHubComment(headCommit string, rep Report) *github.PullRequestComment {
	if len(rep.ModifiedLines) == 1 {
		return &github.PullRequestComment{
			CommitID: github.String(headCommit),
			Path:     github.String(rep.ReportedPath),
			Body:     github.String(rep.Problem.Text),
			Line:     github.Int(rep.ModifiedLines[0]),
		}
	}

	sort.Ints(rep.ModifiedLines)
	start, end := rep.ModifiedLines[0], rep.ModifiedLines[len(rep.ModifiedLines)-1]
	return &github.PullRequestComment{
		CommitID:  github.String(headCommit),
		Path:      github.String(rep.ReportedPath),
		Body:      github.String(rep.Problem.Text),
		Line:      github.Int(end),
		StartLine: github.Int(start),
	}
}
