FROM debian:stable-20231218
RUN apt-get update --yes && \
    apt-get install --no-install-recommends --yes git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY pint-linux-amd64 /usr/local/bin/pint
WORKDIR /code
CMD ["/usr/local/bin/pint"]
