run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofumpt
    - goimports
    - revive
    - misspell
    - promlinter
    - tenv
    - errorlint
    - errname
    - predeclared
    - contextcheck
    - exhaustive
    - gocritic
    - importas
    - nakedret
    - prealloc
    - unconvert
    - testifylint
    - godot
    - copyloopvar
    - perfsprint

issues:
  max-same-issues: 0

linters-settings:
  goimports:
    local-prefixes: github.com/cloudflare/pint
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
  nakedret:
    max-func-lines: 0
