# This Dockerfile is used by goreleaser when releasing a new version.
FROM debian:stable-20260316@sha256:37ad77961af28800b00f5f96a4dfda1855bdcf87f8431033f8b6a549d825bba3
RUN apt-get update --yes && \
    apt-get install --no-install-recommends --yes git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY pint-linux-amd64 /usr/local/bin/pint
WORKDIR /code
CMD ["/usr/local/bin/pint"]
