# This Dockerfile is used by goreleaser when releasing a new version.
FROM debian:stable-20260223@sha256:46137948088890c3079c32df927b1aa59796192c7381501adcf90c15ee325382
RUN apt-get update --yes && \
    apt-get install --no-install-recommends --yes git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY pint-linux-arm64 /usr/local/bin/pint
WORKDIR /code
CMD ["/usr/local/bin/pint"]
