# This Dockerfile is used by goreleaser when releasing a new version.
FROM debian:stable-20251208@sha256:fb368d0a37330ae6039269031552c2d6f5db7dfdad9c6adad026d23be51187d6
RUN apt-get update --yes && \
    apt-get install --no-install-recommends --yes git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY pint-linux-arm64 /usr/local/bin/pint
WORKDIR /code
CMD ["/usr/local/bin/pint"]
