# This Dockerfile is used by goreleaser when releasing a new version.
FROM debian:stable-20260421@sha256:e969bc4a6af81e66bf2ee7e79cecb24885929111d5eddb97dd80bed3b90a5e93
RUN apt-get update --yes && \
    apt-get install --no-install-recommends --yes git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY pint-linux-amd64 /usr/local/bin/pint
WORKDIR /code
CMD ["/usr/local/bin/pint"]
