# This Dockerfile is used by goreleaser when releasing a new version.
FROM debian:stable-20260112@sha256:3b2f658b8c6ca18c5cf954161b0e7038e5d63f724914ef31641d1a5aedbde115
RUN apt-get update --yes && \
    apt-get install --no-install-recommends --yes git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY pint-linux-arm64 /usr/local/bin/pint
WORKDIR /code
CMD ["/usr/local/bin/pint"]
