# This Dockerfile is used by goreleaser when releasing a new version.
FROM debian:stable-20260505@sha256:23759e4f84483a4a2b312eb72e0aa68ad3526344fb2e7caa2eb64846b0d7e142
RUN apt-get update --yes && \
    apt-get install --no-install-recommends --yes git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY pint-linux-amd64 /usr/local/bin/pint
WORKDIR /code
CMD ["/usr/local/bin/pint"]
