groups:
- name: test
  rules:
  - alert: Service Is Down
    expr: up == 0
    for: 0s

  - alert: Service Is Down
    expr: up{xx=bbb} == 0

  - alert: Service Is Down
    expr: up >

  - alert: Service Is Down
    expr: up == 1
    for: 0h
