groups:
- name: test
  rules:
  - record: up:sum
    expr: sum(up)

  - record: up:sum
    expr: sum(up{instance!="none", job=~"bob", job=~"^abc", cluster="dev"})

  - record: up:sum
    expr: |
      sum(up{instance!="none", job=~"bob", job=~"^abc", cluster="dev"})
