name: Validate examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.ver
          cache: false

      - name: Build binary
        run: make

      - name: Generate dummy TLS certificates
        run: |
          sudo mkdir -p /etc/pint/certs
          sudo chmod 777 /etc/pint/certs
          openssl req -x509 -newkey rsa:2048 -keyout /dev/null -out /etc/pint/certs/ca.pem -days 1 -nodes -subj "/CN=test-ca"
          openssl req -x509 -newkey rsa:2048 -keyout /etc/pint/certs/client.key -out /etc/pint/certs/client.pem -days 1 -nodes -subj "/CN=test-client"

      - name: Verify examples
        env:
          AUTH_KEY: "12345"
          PROMETHEUS_AUTH_TOKEN: "abcdef"
        run: |
          for CFG in docs/examples/* ; do
            echo ">>> $CFG"
            ./pint -c "$CFG" config
          done
